export const CAMPS_RECEIVE = 'CAMPS_RECEIVE';
export const CAMPS_REQUEST = 'CAMPS_REQUEST';
export const CAMPS_REQUEST_FAILURE = 'CAMPS_REQUEST_FAILURE';
export const CAMPS_REQUEST_SUCCESS = 'CAMPS_REQUEST_SUCCESS';
export const SESSIONS_RECEIVE = 'SESSIONS_RECEIVE';
export const SESSIONS_REQUEST = 'SESSIONS_REQUEST';
export const SESSIONS_REQUEST_FAILURE = 'SESSIONS_REQUEST_FAILURE';
export const SESSIONS_REQUEST_SUCCESS = 'SESSIONS_REQUEST_SUCCESS';
