export const SESSIONS_RECEIVE = 'SESSIONS_RECEIVE';
export const SESSIONS_REQUEST = 'SESSIONS_REQUEST';
export const SESSIONS_REQUEST_FAILURE = 'SESSIONS_REQUEST_FAILURE';
export const SESSIONS_REQUEST_SUCCESS = 'SESSIONS_REQUEST_SUCCESS';
